name: Unit Test
on:
  pull_request:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  lint:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          go test -v ./...

  swagger:
    name: swagger-docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate Swagger docs
        run: make swagger
